#DEFAULT/DEV ENVIRONEMNT SETTING#

# *** Configuration SERVER ***
server:
   port: 8091
   
# *** Configuration SPRING ***
spring:
   profiles:
      active: "@spring.profiles.active@"
   banner:
      location: classpath:custom-banner.txt

# *** Configuration SECURITY ***
security:
   basic:
      enabled: false


# *** Configuration INFO ACTUATOR ***
info:
   app:
      artifact: "@project.artifactId@"
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      java: "@java.version@"
      encoding: "@project.build.sourceEncoding@"
      environment: "DEFAULT/DEV"