#DEFAULT ENVIRONEMNT SETTING#
server:
   port: 8086
   
spring:
   h2:
    console:
      enabled: true
   flyway:
      enabled: true
      locations: 
         - "classpath:db/migration"
   jpa:
      hibernate:
         dialect: org.hibernate.dialect.H2Dialect
         show-sql: true
         ddl-auto: validate
      #generate-ddl: true
      #properties:
      #   hibernate:
            #dialect: org.hibernate.dialect.H2Dialect
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:acme;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
      username: sa
      password: sa
      #drop-first: true
      #default-schema: acme



      